/** Arrow bits: N, NE, E, SE, S, SW, W, NW */
export const DIR = {
  N: 1,
  NE: 2,
  E: 4,
  SE: 8,
  S: 16,
  SW: 32,
  W: 64,
  NW: 128,
};

export const DIRECTIONS = [
  { bit: DIR.N, key: 'N', dr: -1, dc: 0, opposite: DIR.S },
  { bit: DIR.NE, key: 'NE', dr: -1, dc: 1, opposite: DIR.SW },
  { bit: DIR.E, key: 'E', dr: 0, dc: 1, opposite: DIR.W },
  { bit: DIR.SE, key: 'SE', dr: 1, dc: 1, opposite: DIR.NW },
  { bit: DIR.S, key: 'S', dr: 1, dc: 0, opposite: DIR.N },
  { bit: DIR.SW, key: 'SW', dr: 1, dc: -1, opposite: DIR.NE },
  { bit: DIR.W, key: 'W', dr: 0, dc: -1, opposite: DIR.E },
  { bit: DIR.NW, key: 'NW', dr: -1, dc: -1, opposite: DIR.SE },
];

export const ELEMENTS = ['fire', 'ice', 'water', 'wind', 'earth', 'thunder', 'holy', 'dark', 'poison'];

/** Attacker element beats this defender element. */
export const ELEMENT_BEATS = {
  fire: 'ice',
  ice: 'water',
  water: 'fire',
  wind: 'earth',
  earth: 'thunder',
  thunder: 'wind',
  holy: 'dark',
  dark: 'poison',
  poison: 'holy',
};

const A = DIR;

/**
 * Original dark-fantasy roster. Names, stats, and arrows are original.
 * Archetypes nod at classic JRPG bosses and infernal warlords without copying them.
 */
export const ROSTER = [
  {
    id: 'ashen-phoenix',
    name: 'Ashen Phoenix',
    title: 'Cinder Sovereign',
    attack: 8,
    type: 'P',
    pdef: 4,
    mdef: 6,
    arrows: A.N | A.NE | A.E | A.SW,
    element: 'fire',
    art: 'phoenix',
  },
  {
    id: 'gravewing',
    name: 'Gravewing',
    title: 'Bone Tyrant',
    attack: 7,
    type: 'M',
    pdef: 5,
    mdef: 8,
    arrows: A.N | A.W | A.E | A.S,
    element: 'dark',
    art: 'gravewing',
  },
  {
    id: 'tidebreaker',
    name: 'Tidebreaker',
    title: 'Abyss Coil',
    attack: 6,
    type: 'P',
    pdef: 7,
    mdef: 5,
    arrows: A.W | A.SW | A.S | A.SE,
    element: 'water',
    art: 'serpent',
  },
  {
    id: 'stormglass',
    name: 'Stormglass Oracle',
    title: 'Sky-Scribe',
    attack: 5,
    type: 'M',
    pdef: 3,
    mdef: 9,
    arrows: A.N | A.NE | A.NW,
    element: 'thunder',
    art: 'oracle',
  },
  {
    id: 'iron-vow',
    name: 'Iron Vow',
    title: 'Oath Paladin',
    attack: 7,
    type: 'P',
    pdef: 9,
    mdef: 4,
    arrows: A.N | A.S | A.W,
    element: 'holy',
    art: 'paladin',
  },
  {
    id: 'voidglass',
    name: 'Voidglass Lich',
    title: 'Last Phylactery',
    attack: 6,
    type: 'M',
    pdef: 4,
    mdef: 8,
    arrows: A.E | A.SE | A.S | A.SW,
    element: 'dark',
    art: 'lich',
  },
  {
    id: 'bloodmoon',
    name: 'Bloodmoon Duelist',
    title: 'Crimson Step',
    attack: 9,
    type: 'P',
    pdef: 3,
    mdef: 3,
    arrows: A.NE | A.E | A.SE,
    element: 'poison',
    art: 'duelist',
  },
  {
    id: 'thornwake',
    name: 'Thornwake Matron',
    title: 'Bloom of Knives',
    attack: 4,
    type: 'P',
    pdef: 8,
    mdef: 6,
    arrows: A.N | A.S | A.E | A.W,
    element: 'earth',
    art: 'matron',
  },
  {
    id: 'cinder-behemoth',
    name: 'Cinder Behemoth',
    title: 'Furnace Hide',
    attack: 8,
    type: 'P',
    pdef: 8,
    mdef: 2,
    arrows: A.N | A.NW | A.W | A.SW,
    element: 'fire',
    art: 'behemoth',
  },
  {
    id: 'hellforge',
    name: 'Hellforge Tyrant',
    title: 'Crown of Cinders',
    attack: 10,
    type: 'A',
    pdef: 6,
    mdef: 6,
    arrows: A.N | A.NE | A.E | A.SE | A.S,
    element: 'fire',
    art: 'tyrant',
  },
  {
    id: 'gilded-colossus',
    name: 'Gilded Colossus',
    title: 'Judgment Engine',
    attack: 7,
    type: 'A',
    pdef: 8,
    mdef: 8,
    arrows: A.N | A.E | A.S | A.W,
    element: 'holy',
    art: 'colossus',
  },
  {
    id: 'nightbloom',
    name: 'Nightbloom Witch',
    title: 'Hex Orchard',
    attack: 5,
    type: 'M',
    pdef: 4,
    mdef: 7,
    arrows: A.NW | A.N | A.NE | A.E,
    element: 'poison',
    art: 'witch',
  },
  {
    id: 'rift-stalker',
    name: 'Rift Stalker',
    title: 'Between-Worlds',
    attack: 8,
    type: 'X',
    pdef: 5,
    mdef: 5,
    arrows: A.NE | A.SE | A.SW | A.NW,
    element: 'dark',
    art: 'stalker',
  },
  {
    id: 'bone-choir',
    name: 'Bone Choir',
    title: 'Red Cantor',
    attack: 6,
    type: 'M',
    pdef: 5,
    mdef: 7,
    arrows: A.N | A.E | A.S,
    element: 'dark',
    art: 'choir',
  },
  {
    id: 'skyraid',
    name: 'Skyraid Wyvern',
    title: 'Gale Lance',
    attack: 7,
    type: 'P',
    pdef: 4,
    mdef: 5,
    arrows: A.N | A.NE | A.NW | A.E,
    element: 'wind',
    art: 'wyvern',
  },
  {
    id: 'abyssal-countess',
    name: 'Abyssal Countess',
    title: 'Velvet Cataclysm',
    attack: 8,
    type: 'M',
    pdef: 5,
    mdef: 9,
    arrows: A.W | A.SW | A.S | A.SE | A.E,
    element: 'water',
    art: 'countess',
  },
  {
    id: 'runebound',
    name: 'Runebound Golem',
    title: 'Law of Stone',
    attack: 5,
    type: 'P',
    pdef: 11,
    mdef: 6,
    arrows: A.N | A.S | A.E | A.W | A.SE,
    element: 'earth',
    art: 'golem',
  },
  {
    id: 'pearl-seraph',
    name: 'Pearl Seraph',
    title: 'Dawnwarden',
    attack: 6,
    type: 'M',
    pdef: 6,
    mdef: 8,
    arrows: A.N | A.NE | A.NW | A.S,
    element: 'holy',
    art: 'seraph',
  },
  {
    id: 'plaguebloom',
    name: 'Plaguebloom',
    title: 'Sweet Rot',
    attack: 4,
    type: 'X',
    pdef: 7,
    mdef: 7,
    arrows: A.S | A.SW | A.SE | A.W,
    element: 'poison',
    art: 'plague',
  },
  {
    id: 'ember-drake',
    name: 'Ember Drake',
    title: 'Kindling Prince',
    attack: 6,
    type: 'P',
    pdef: 5,
    mdef: 4,
    arrows: A.E | A.SE | A.S,
    element: 'fire',
    art: 'drake',
  },
  {
    id: 'frost-wraith',
    name: 'Frost Wraith',
    title: 'Hollow Thaw',
    attack: 5,
    type: 'M',
    pdef: 4,
    mdef: 10,
    arrows: A.N | A.W | A.NW,
    element: 'ice',
    art: 'wraith',
  },
  {
    id: 'shard-knight',
    name: 'Shard Knight',
    title: 'Glass Crusade',
    attack: 7,
    type: 'X',
    pdef: 7,
    mdef: 7,
    arrows: A.N | A.NE | A.S | A.SW,
    element: 'ice',
    art: 'shard',
  },
];

export function hexDigit(n) {
  const clamped = Math.max(0, Math.min(15, n | 0));
  return '0123456789ABCDEF'[clamped];
}

export function cardById(id) {
  return ROSTER.find((c) => c.id === id);
}
